language: java
sudo: enabled

addons:
  postgresql: "9.6"

before_script:
  - psql -c "create database aries;" -U scrambledb // your database name
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password '0885087'"

services:
  - postgresql

before_install:
  - chmod +x mvnw

