language: java
#sudo: enabled
#
#addons:
#  postgresql: "9.6"
#
#before_script:
#  - psql -c "create database aries;" -U scrambledb // your database name
#  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password '0885087'"
#
#services:
#  - postgresql

addons:
  sonarcloud:
    organization: "scrambleminor" # the key of the org you chose at step #3
script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=JJGreep_Scramble-backend

#branches:
#  only:
#    - master

before_install:
  - chmod +x mvnw

